// Issue #7580

//@ run-fail
//@ check-run-results
//@ needs-subprocess

use std::*;

fn main() {
    panic!("panic works")
}
